import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

import Header from "@/src/components/Header";
import Footer from "@/src/components/Footer";

import WhatsAppButton from "@/src/components/WhatsappButton";
import ScrollProgressCircle from "@/src/components/ScrollProgressCircle";
import CustomCursor from "@/src/components/CustomCursor";
import { ThemeProvider } from "@/src/components/ThemeProvider";
import ThemeToggle from "@/src/components/ThemeToggle";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300","400","500","600","700","800"],
});

export const metadata: Metadata = {
  title: "BZ Analytics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${plusJakarta.className} antialiased bg-[#101010]`}>

        <ThemeProvider attribute="class" defaultTheme="dark">

          <div className="min-h-screen flex flex-col">

            <Header />

            <main className="flex-grow">
              {children}
            </main>

            <Footer />

          </div>

          <ThemeToggle />
          <CustomCursor />
          <ScrollProgressCircle />
          <WhatsAppButton />

        </ThemeProvider>

      </body>
    </html>
  );
}